### ISSUE TITLE
Both Fahrenheit and Celsius temperature scale in `espresso_temperature_mix` series data

### ISSUE THREAD

**Issue by JonnyTran** [ebengoechea/dye_de1app_dsx_plugin#16]
The raw temperature data collected by DYE doesn't yet convert between Fahrenheit and Celsius, and since users can either set C or F in their machine, the raw data collected are not on the same scale and will cause issues in data analysis.
 
I found this looking at the histogram of the maximum `espresso_temperature_mix` series in Visualizer.coffee shots data, it shows that there's a bimodal distribution centered around 90 and 192, indicating that the former is temperature data points in Celsius and the latter in Fahrenheit.

@ebengoechea Could you convert all `espresso_temperature_mix`, `espresso_temperature_basket`, `espresso_temperature_goal` to Celsius if the machine data was set to Fahrenheit, especially before it automatically uploads to Visualizer.Coffee?

**Comment by ebengoechea** [comment]
It's not DYE, it's how the app records and stores it on the shot files. Any problem on those series belongs to the base app and should be reported in Diaspora in the programming threads, including the problem series data.

**Comment by JonnyTran** [comment]
I'll repost this issue elsewhere then. Thanks @ebengoechea.
