### ISSUE TITLE
DYE DSX2 bug under extraction

### ISSUE THREAD

**Issue by rhys100** [ebengoechea/dye_de1app_dsx_plugin#17]
![image](https://github.com/ebengoechea/dye_de1app_dsx_plugin/assets/8174496/8a6bca02-39d0-45a4-a760-08f146fb5e2b)

**Comment by ebengoechea** [comment]
Already fixed and merged into main app: [https://github.com/decentespresso/de1app/pull/278]() and [https://github.com/decentespresso/de1app/pull/286]().

The current DYE repo is not this but [https://github.com/ebengoechea/de1app_plugin_DYE]()
